version: '3.8'

services:
  node:
    user: node
    image: node:alpine
    container_name: node-alpine
    hostname: node-alpine
    working_dir: /app
    volumes:
      - ./src:/app
    command: sh -c "npm install && node index.js"
    networks:
      - osm-net

  nginx:
    image: nginx:alpine
    container_name: nginx-alpine
    hostname: nginx-alpine
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
    networks:
      - osm-net
    ports:
      - 8080:80
    depends_on:
      - node

networks:
  osm-net:
    driver: bridge
