version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    hostname: mysql
    command: --innodb-use-native-aio=0
    networks:
      - osm-net
    volumes:
      - ./database:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_ROOT_PASSWORD=root
    restart: always
    healthcheck:
      test:
        [
          "CMD",
          "mysql",
          "-uroot",
          "-proot",
          "-qfsBe",
          "SELECT SCHEMA_NAME FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME='db'"
        ]
      interval: 5s
      timeout: 30s
      retries: 10

  node:
    user: node
    image: node:alpine
    container_name: node-alpine
    hostname: node-alpine
    working_dir: /app
    command: sh -c "npm install && node index.js"
    restart: always
    volumes:
      - ./src:/app
    networks:
      - osm-net
    depends_on:
      mysql:
        condition: service_healthy

  nginx:
    image: nginx:alpine
    container_name: nginx-alpine
    hostname: nginx-alpine
    restart: always
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
    networks:
      - osm-net
    ports:
      - 8080:80
    depends_on:
      - node

networks:
  osm-net:
    driver: bridge
